Repository michaelrsweet/lprint, pull requests merged in 2022-11, with the labels that each got.

#79 Fix mode_configured/mode_supported typo
  lprint-epl2.c
  lprint-zpl.c
Labels: bug, priority-high

#85 configure.ac: Fix bindir expansion (fixes #81)
  configure
  configure.ac
Labels: bug, priority-high, platform issue

#56 Fix EPL2 list (Issue #52)
  lprint-epl2.h
Labels: bug, priority-medium

#82 Default the log level to info in the systemd service
  lprint.service.in
Labels: enhancement, priority-low, platform issue
